# Generated by Django 5.1 on 2024-08-31 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('flat_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_purchase', models.DateTimeField()),
                ('date_of_sale_agreement', models.DateTimeField()),
                ('date_of_sale_deed', models.DateTimeField(blank=True)),
                ('date_of_register_sale_agreement', models.DateTimeField(blank=True)),
                ('seller_name', models.TextField(max_length=50)),
                ('seller_type', models.TextField(max_length=50)),
                ('doc_image', models.FileField(upload_to='files')),
                ('flat_no', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='members.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='EmailID',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('flat_no', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='members.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('phone_number', models.IntegerField(primary_key=True, serialize=False)),
                ('alternate_number', models.IntegerField(blank=True)),
                ('flat_no', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='members.userdetails')),
            ],
        ),
    ]
