# Generated by Django 5.1 on 2024-08-31 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=30)),
                ('loan_amount', models.IntegerField(max_length=10)),
                ('amount_processed', models.IntegerField(max_length=10)),
                ('amount_pending', models.IntegerField(max_length=10)),
                ('emi_status', models.BooleanField()),
                ('loan_status', models.BooleanField()),
                ('flat_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ReraComplaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_refund_file', models.DateTimeField()),
                ('date_of_refund_order_execution', models.DateTimeField(blank=True)),
                ('date_of_joining_association', models.DateTimeField()),
                ('bank_emi_stop_date', models.DateTimeField(blank=True)),
                ('doc_image', models.FileField(upload_to='files')),
                ('flat_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.userdetails')),
            ],
        ),
    ]
